# Generated by Django 3.2.8 on 2021-11-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('start_dt', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_dt', models.DateTimeField(verbose_name='Fecha de fin')),
            ],
            options={
                'verbose_name': 'Plazo',
                'verbose_name_plural': 'Plazos',
                'ordering': ('end_dt',),
            },
        ),
    ]
