# Generated by Django 3.2.8 on 2021-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='module',
            field=models.CharField(max_length=100, verbose_name='Módulo'),
        ),
    ]
