# Generated by Django 3.2.8 on 2022-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadlines', '0002_alter_deadline_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='announcement',
            field=models.IntegerField(default=60, verbose_name='Convocatoria (0=No confirmada)'),
        ),
    ]
