# Generated by Django 3.2.8 on 2021-11-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circumscription', '0002_auto_20211104_1505'),
        ('council_member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councilmember',
            name='district',
        ),
        migrations.AddField(
            model_name='councilmember',
            name='circumscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_member_circumscription_set', to='circumscription.circumscription', verbose_name='Circunscripción'),
        ),
    ]
