# Generated by Django 3.2.8 on 2022-01-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_member', '0002_auto_20211104_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councilmember',
            old_name='circumscription',
            new_name='circumscription_vote',
        ),
        migrations.AddField(
            model_name='councilmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de correo electrónico'),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave'),
        ),
    ]
