# Generated by Django 3.2.8 on 2022-02-16 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circumscription', '0002_auto_20211104_1505'),
        ('council_member', '0003_auto_20220103_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmember',
            name='circumscription_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_member_circumscription_set', to='circumscription.circumscription', verbose_name='Circunscripción'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='council_member_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='councilmember',
            name='voting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de votación'),
        ),
    ]
