# Generated by Django 3.2.8 on 2022-03-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('council_member', '0004_auto_20220216_0259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='councilmember',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Miembro del consejo', 'verbose_name_plural': 'Miembros del consejo'},
        ),
        migrations.AddField(
            model_name='councilmember',
            name='dni_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Documento de indentidad'),
        ),
    ]
