# Generated by Django 3.2.8 on 2022-01-04 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circumscription', '0002_auto_20211104_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos')),
                ('dni_number', models.CharField(blank=True, max_length=200, verbose_name='Documento de indentidad')),
                ('associate_number', models.CharField(max_length=200, verbose_name='Número de socio/a')),
                ('associate_dt', models.DateField(blank=True, null=True, verbose_name='Fecha antigüedad')),
                ('voting_date', models.DateTimeField(null=True, verbose_name='Fecha de votación')),
                ('birthday', models.DateTimeField(null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de correo electrónico')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clave')),
                ('circumscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_circumscription_set', to='circumscription.circumscription', verbose_name='Circunscripción')),
                ('circumscription_vote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_circumscription_vote_set', to='circumscription.circumscription', verbose_name='Circunscripción voto')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associate_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
    ]
