# Generated by Django 3.2.8 on 2022-01-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circumscription', '0002_auto_20211104_1505'),
        ('associate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='circumscription_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associate_circumscription_vote_set', to='circumscription.circumscription', verbose_name='Circunscripción voto'),
        ),
        migrations.AlterField(
            model_name='associate',
            name='voting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de votación'),
        ),
    ]
