# Generated by Django 3.2.8 on 2022-03-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associate', '0002_auto_20220113_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associate',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
