# Generated by Django 3.2.8 on 2021-11-04 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circumscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=100)),
                ('prefix_cp', models.CharField(max_length=2)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_district_set', to='circumscription.circumscription')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
    ]
