# Generated by Django 3.2.8 on 2021-11-04 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circumscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateTimeField(auto_now=True, verbose_name='Fecha presentación candidatura')),
                ('firstname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('seniority_date', models.DateTimeField(null=True, verbose_name='Fecha antigüedad')),
                ('description', models.TextField(blank=True, max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Breve descripción -máximo 150 caracteres')),
                ('curriculum_vitae', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Currículum profesional -máximo 1.000 caracteres')),
                ('bonding', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Vinculación con Greenpeace -máximo 1.000 caracteres')),
                ('motivation', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Motivación para presentar la candidatura -máximo 1.000 caracteres')),
                ('campaign', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Campaña')),
                ('comments', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Comentarios')),
                ('allegations', models.TextField(blank=True, max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Alegaciones')),
                ('dni_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('active_participation', models.BooleanField()),
                ('up_to_date', models.BooleanField(default=True)),
                ('veracity', models.BooleanField()),
                ('antiquity_3_years', models.BooleanField()),
                ('on_the_council', models.BooleanField(default=False)),
                ('circumscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidature_circumscription_set', to='circumscription.circumscription', verbose_name='Circunscripción')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
            },
        ),
    ]
