# Generated by Django 3.2.8 on 2021-11-11 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council_member', '0002_auto_20211104_1505'),
        ('candidatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='announcement',
            field=models.IntegerField(default=0, verbose_name='Convocatoria (0=No confirmada)'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='dni',
            field=models.FileField(default=1, upload_to='%Y/%m/%d', verbose_name='Copia del DNI/ Pasaporte/ Tarjeta de residente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='¿Es mayor de edad?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='locality',
            field=models.CharField(default=1, max_length=200, verbose_name='Localidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='participation',
            field=models.TextField(blank=True, max_length=300, validators=[django.core.validators.MaxLengthValidator(300)], verbose_name='Participación'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='partner_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Nº de socio/a'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Foto -máximo 200kB-'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='presents_it',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_council_member_set', to='council_member.councilmember'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='validated',
            field=models.BooleanField(default=True, verbose_name='Validada por la Comisión Electoral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidature',
            name='validated_by_system',
            field=models.BooleanField(default=False, verbose_name='Comprobada por el sistema'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='validated_circumscription',
            field=models.BooleanField(default=False, verbose_name='Circunscripción correcta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidature',
            name='active_participation',
            field=models.BooleanField(verbose_name='Compromiso de participación activa: Al presentar esta candidatura adquiero el compromiso, en caso de resultar elegido/a, de participar activamente en las tareas que el Consejo tiene señaladas o se señalen.'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='antiquity_3_years',
            field=models.BooleanField(verbose_name='Antigüedad > 3 años'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='dni_number',
            field=models.CharField(max_length=100, verbose_name='Número y letra del DNI/ Pasaporte/ Tarjeta de residente'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico para facilitar a la comisión electoral la resolución de errores'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='on_the_council',
            field=models.BooleanField(default=False, verbose_name='Actualmente en el Consejo'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='up_to_date',
            field=models.BooleanField(default=True, verbose_name='Al corriente de pago'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='veracity',
            field=models.BooleanField(verbose_name='Doy fe de la veracidad de los datos'),
        ),
    ]
