# Generated by Django 3.2.8 on 2021-11-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0005_auto_20211117_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='seniority_date',
            field=models.DateField(null=True, verbose_name='Fecha antigüedad'),
        ),
    ]
