# Generated by Django 3.2.8 on 2021-11-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council_member', '0002_auto_20211104_1505'),
        ('candidatures', '0006_alter_candidature_seniority_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='presents_it',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidature_council_member_set', to='council_member.councilmember', verbose_name='¿Quien lo presenta?'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='presents_it_dni',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='Miembro del Consejo que presenta al candidato/a: Copia del DNI/ Pasaporte/ Tarjeta de residente'),
        ),
    ]
