# Generated by Django 3.2.8 on 2021-12-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0008_alter_candidature_seniority_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='is_allegate',
            field=models.BooleanField(default=False, verbose_name='Tiene alegaciones'),
        ),
    ]
