# Generated by Django 3.2.8 on 2022-01-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0009_candidature_is_allegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validada'),
        ),
    ]
