# Generated by Django 3.2.8 on 2022-01-13 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0010_alter_candidature_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='bonding',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Vinculación con Greenpeace -máximo 1.000 caracteres'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='campaign',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='¿Qué cambios te gustaría ver en Greenpeace en los próximos tres años? -máximo 1.000 caracteres'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='curriculum_vitae',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Currículum profesional -máximo 1.000 caracteres'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='motivation',
            field=models.TextField(max_length=1000, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Motivación para presentar la candidatura -máximo 1.000 caracteres'),
        ),
    ]
