# Generated by Django 3.2.8 on 2022-01-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0011_auto_20220113_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='is_allegate',
            field=models.BooleanField(default=True, verbose_name='Tiene alegaciones'),
        ),
    ]
