# Generated by Django 3.2.8 on 2022-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0012_alter_candidature_is_allegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='is_allegate',
            field=models.BooleanField(default=False, verbose_name='Tiene alegaciones'),
        ),
    ]
