# Generated by Django 3.2.8 on 2022-02-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0013_alter_candidature_is_allegate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='dni_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número y letra del DNI/ Pasaporte/ Tarjeta de residente'),
        ),
    ]
