# Generated by Django 3.2.8 on 2022-02-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('candidatures', '0015_alter_candidature_dni_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='habeas_data',
            field=models.BooleanField(default=False,
                                      verbose_name='Acepta que los datos aquí ingresados sea de uso público'),
        ),
    ]
