# Generated by Django 3.2.8 on 2022-03-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0016_candidature_habeas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='habeas_data',
            field=models.BooleanField(default=False, verbose_name='Acepta que los datos aportados serán visibles para los socios de Greenpeace'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='up_to_date',
            field=models.BooleanField(default=False, verbose_name='Al corriente de pago'),
        ),
    ]
