# Generated by Django 3.2.8 on 2022-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatures', '0017_auto_20220301_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='active_participation',
            field=models.BooleanField(verbose_name='La candidatura presentada se compromete, en caso de resultar elegido/a, de participar activamente en las tareas que el Consejo tiene asignadas.'),
        ),
    ]
