# Generated by Django 3.2.8 on 2021-11-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circumscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds', models.CharField(max_length=100)),
                ('alize', models.CharField(max_length=100)),
                ('cod_ine', models.CharField(max_length=2)),
                ('places', models.IntegerField()),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Circunscripcion',
                'verbose_name_plural': 'Circunscipciones',
                'ordering': ['order', 'ds'],
            },
        ),
    ]
