# Generated by Django 3.2.8 on 2022-03-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circumscription', '0002_auto_20211104_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circumscription',
            options={'ordering': ['ds', 'order'], 'verbose_name': 'Circunscripcion', 'verbose_name_plural': 'Circunscipciones'},
        ),
    ]
