# Generated by Django 3.2.8 on 2022-03-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circumscription', '0003_alter_circumscription_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='circumscription',
            name='associate_number',
            field=models.IntegerField(default=60, verbose_name='Número de socios'),
            preserve_default=False,
        ),
    ]
